//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalKalina_Zadanie_Domowe_Lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Customer
    {
        public int CustomerID { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
    }
}
